# 開発作業用テンプレート
# 使い方: tmuxinator start dev [project_path]
#         dev [path|alias]
#
# レイアウト:
# Window 1 (dev):
# ┌─────────┬─────────────────────┐
# │  yazi   │                     │
# ├─────────┤     terminal        │
# │   tig   │                     │
# └─────────┴─────────────────────┘
#    35%             65%
#
# Window 2 (git): lazygit

name: dev
root: <%= @args[0] || "." %>

windows:
  - dev:
      layout: main-vertical
      options:
        main-pane-width: 65%
      panes:
        - ""           # 右: メインターミナル (65%)
        - yazi         # 左上: ファイルツリー
        - tig          # 左下: gitログ

  - git: lazygit
