# 開発作業用テンプレート
# 使い方: tmuxinator start dev [project_path]
#         dev [path|alias]
#
# レイアウト:
# Window 1 (dev):
# ┌──────────────┬─────────────────────┐
# │  filetree    │                     │
# ├──────────────┤     terminal        │
# │ git-summary  │                     │
# └──────────────┴─────────────────────┘
#      35%                65%
#
# Window 2 (git): lazygit

name: dev
root: <%= @args[0] || "." %>

windows:
  - dev:
      layout: main-vertical
      options:
        main-pane-width: 65%
      panes:
        - ""                              # 右: メインターミナル (65%)
        - ft                              # 左上: ファイルツリー
        - watch -c -n 2 git-summary       # 左下: git状態

  - git: lazygit
