# 開発作業用テンプレート
# 使い方: tmuxinator start dev [project_path]
# 例: tmuxinator start dev ~/projects/myapp

name: dev
root: <%= @args[0] || "." %>

windows:
  - editor:
      panes:
        - # メインエディタ用
  - shell:
      layout: even-horizontal
      panes:
        - # 作業用シェル1
        - # 作業用シェル2
  - server:
      panes:
        - # サーバー/ビルド用
