# 開発作業用テンプレート
# 使い方: tmuxinator start dev [project_path]
#         dev [path|alias]
#
# レイアウト:
# Window 1 (dev):
# ┌──────────┬──────────────────┐
# │  yazi    │   claude code    │
# ├──────────┼──────────────────┤
# │ lazygit  │   terminal       │
# └──────────┴──────────────────┘

name: dev
root: <%= @args[0] || "." %>

windows:
  - dev:
      layout: tiled
      panes:
        - yazi         # 左上: ファイラー
        - claude       # 右上: claude code
        - lazygit      # 左下: git
        - ""           # 右下: ターミナル
