# 開発作業用テンプレート
# 使い方: tmuxinator start dev [project_path]

name: dev
root: <%= @args[0] || "." %>

windows:
  - main:
      layout: main-vertical
      panes:
        - # メイン（左・大）
        - # サブ（右上）
        - # サブ（右下）
