# 開発作業用テンプレート
# 使い方: tmuxinator start dev [project_path]
#         dev [path|alias]
#
# レイアウト:
# Window 1 (dev):
# ┌──────────┬──────────────────┐
# │  yazi    │   claude code    │  65%
# ├──────────┼──────────────────┤
# │ lazygit  │   terminal       │  35%
# └──────────┴──────────────────┘

name: <%= @args[1] || "dev" %>
root: <%= @args[0] || "." %>

windows:
  - dev:
      layout: tiled
      panes:
        - yazi         # 左上: ファイラー
        - claude       # 右上: claude code
        - lazygit      # 左下: git
        -              # 右下: ターミナル
          - tmux resize-pane -t '<%= @args[1] || "dev" %>:1.1' -y 65%
