# 開発作業用テンプレート
# 使い方: tmuxinator start dev [project_path]
#         dev [path|alias]
#
# レイアウト:
# ┌─────────┬─────────────────────┐
# │  yazi   │                     │
# ├─────────┤     terminal        │
# │ lazygit │                     │
# └─────────┴─────────────────────┘

name: dev
root: <%= @args[0] || "." %>

windows:
  - dev:
      layout: main-vertical
      options:
        main-pane-width: 65%
      panes:
        - ""           # 右: メインターミナル
        - yazi         # 左上: ファイルツリー
        - lazygit      # 左下: git
