# 開発作業用テンプレート
# 使い方: tmuxinator start dev [project_path]
#         dev [path|alias]
#
# レイアウト:
# Window 1 (dev):
# ┌──────────┬──────────────────┐
# │  yazi    │   claude code    │
# ├──────────┤                  │
# │ lazygit  ├──────────────────┤
# │          │   terminal       │
# └──────────┴──────────────────┘
#     35%            65%

name: dev
root: <%= @args[0] || "." %>

windows:
  - dev:
      layout: main-vertical
      options:
        main-pane-width: 65%
      panes:
        - claude       # 右上: claude code (メインペイン 65%)
        - yazi         # 左上: ファイラー
        - lazygit      # 左下: git
        - ""           # 右下: ターミナル
